#!/bin/bash

set -eu
# set -vx

source host.conf

# Generate a new /etc/resolv.conf ...
dns_search_domains_csv=$( r_join dns_search_domains[@] "," )
echo "dns_domain = $dns_domain"
echo "dns_search_domains = ${dns_search_domains[@]}"
echo "dns_search_domains_csv = $dns_search_domains_csv"

cat <<ENDOFRESOLVCONF >/etc/resolv.conf
# Generated by the XDAHM post-install script
#  on $(date)

domain $dns_domain
ENDOFRESOLVCONF

r_join dns_search_domains[@]  ' '   | sed 's/^/search /'    >> /etc/resolv.conf
r_join dns_servers[@]         $'\n' | sed 's/^/nameserver /'  >> /etc/resolv.conf


# Set the DNS search domains on the management interfaces
host_name_label="$(xe host-list params=name-label --minimal)";
management_pifs=( $(xe pif-list host-name-label="$host_name_label"  \
                        management=true                             \
                        params=uuid --minimal                       \
                        | sed 's/,/\n/g'                            \
                    ) );

for management_pif in "${management_pifs[@]}"; do
  xe pif-param-set uuid="$management_pif"   \
    other-config:domain="$dns_domain,$dns_search_domains_csv"
done


# Test DNS Resolution
#  XenServer does not include nslookup(1) or dig(1)
#  so use ping instead
ping -W 2 -c 1 "$(hostname -d)"  || true
ping -W 2 -c 1 "$(hostname -f)"  || true
